<?php
// $Id$

/**
 * @file
 * Creates settings page and inserts the javascript onto the site's pages.
 */

function beautytips_admin() {
  $form['beautytips_turnon'] = array(
    '#type' => 'checkbox',
    '#title' => 'Turn on Beauty Tips',
    '#default_value' => variable_get('beautytips_turnon', FALSE),
  );
  $form['beautytips_direction'] = array(
    '#type' => 'radios',
    '#title' => 'Which side should the popup appear on?',
    '#options' => array('bottom' => t('bottom'), 'top' => t('top'), 'left' => t('left'), 'right' => t('right')),
    '#default_value' => variable_get('beautytips_direction', 'bottom'),
  );
  $form['#submit'][] = 'beautytips_admin_submit';
  return system_settings_form($form);
}

function beautytips_admin_submit() {
  drupal_rebuild_theme_registry();
}

/**
 * Implementation of hook_menu.
 */
function beautytips_menu() {
  $items = array();
  $items['admin/settings/beautytips'] = array(
    'title' => 'Beauty Tips settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('beautytips_admin'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}
 
/**
 * Implementation of hook_theme_registry_alter.
 */
function beautytips_theme_registry_alter(&$theme_registry) {
  if (variable_get('beautytips_turnon', FALSE)) {
    $theme_registry['form']['function'] = 'theme_beautytips_form';
  }
}

/**
 * Override of theme_form.
 */
function theme_beautytips_form($element) {
  // Add a jQuery script for the popups
  $path = drupal_get_path('module', 'beautytips');
  drupal_add_js("var bt_direction = " . drupal_to_js(variable_get('beautytips_direction', 'bottom')) . ";", 'inline');
  drupal_add_js( $path .'/jquery.bt.js');
  drupal_add_js( $path .'/beautytips.js');
  drupal_add_css($path .'/jquery.bt.css');

  // Anonymous div to satisfy XHTML compliance.
  $action = $element['#action'] ? 'action="'. check_url($element['#action']) .'" ' : '';
  return '<form '. $action .' accept-charset="UTF-8" method="'. $element['#method'] .'" id="'. $element['#id'] .'"'. drupal_attributes($element['#attributes']) .">\n<div>". $element['#children'] ."\n</div></form>\n";
}