<?php
// $Id$

/**
 * @file
 * Creates beautyips settings page and adds beautytips popups.
 */

function beautytips_admin() {
  $form['beautytips_turnon'] = array(
    '#type' => 'checkbox',
    '#title' => 'Turn on Beauty Tips',
    '#default_value' => variable_get('beautytips_turnon', FALSE),
  );
  $form['beautytips_drupal_help'] = array(
    '#type' => 'checkbox',
    '#title' => 'Turn on help link popups',
    '#default_value' => variable_get('beautytips_drupal_help', FALSE),
  );
  $form['beautytips_direction'] = array(
    '#type' => 'radios',
    '#title' => 'Which side should the popup appear on?',
    '#options' => array('bottom' => t('bottom'), 'top' => t('top'), 'left' => t('left'), 'right' => t('right')),
    '#default_value' => variable_get('beautytips_direction', 'bottom'),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_menu.
 */
function beautytips_menu() {
  $items = array();
  $items['admin/settings/beautytips'] = array(
    'title' => 'Beautytips',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('beautytips_admin'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}
 
/**
 * Implementation of hook_form_alter.
 */
function beautytips_form_alter(&$form, $form_state, $form_id) {
  if (variable_get('beautytips_turnon', FALSE)) {
    $path = drupal_get_path('module', 'beautytips');
    drupal_add_js("var bt_direction = " . drupal_to_js(variable_get('beautytips_direction', 'bottom')) . ";", 'inline');
    drupal_add_js($path .'/beautytips.js');    

    $options = array();
    $options['bt_text_field'] = array(
        'area' => 'input.form-text',
        'trigger' => array(0 => 'focus', 1 => 'blur'),
        'description' => TRUE,
      );
    $options['bt_text_area'] = array(
      'area' => 'textarea.form-textarea',
      'trigger' => array(0 => 'focus', 1 => 'blur'),
      'description' => TRUE,
    );
    beautytips_add_beautytips($options);
  }
  if (variable_get('beautytips_drupal_help', FALSE)) {
     $options = array();
     $options['bt_drupal_help'] = array(
        'area' => '.more-help-link a',
        'description' => FALSE,
        'ajaxPath' => "$(this).attr('href')",
        'ajaxDiv' => '#squeeze.clear-block p',
     );
     beautytips_add_beautytips($options);
  }
  elseif (!variable_get('beautytips_turnon', FALSE)) {
    beautytips_add_beautytips();
  }
}

function beautytips_add_beautytips($options = NULL) {
  static $added = FALSE;
  $settings = array('beautytips' => array());
  
  if (is_array($options)) {
    $settings['beautytips'] = array();
      foreach ($options as $beautytip => $content) {
        if (is_array($content)) {
          $settings['beautytips'][$beautytip] = $content;
          if (!isset($content['ajaxPath'])) {
            $settings['beautytips'][$beautytip]['ajaxPath'] = NULL;
            $settings['beautytips'][$beautytip]['ajaxDiv'] = NULL;
          }
          if (!isset($content['trigger'])) {
            $settings['beautytips'][$beautytip]['trigger'] = 'hover';
          }
        }
      }
  }
  
  // Add beautytips jQuery plugin
  if (!$added) {
    $path = drupal_get_path('module', 'beautytips');
    drupal_add_js($path .'/jquery.bt.js');
    drupal_add_css($path .'/jquery.bt.css');
    
    //if IE add this
    drupal_add_js($path .'/other_libs/ex_canvas_0002/excanvas.js');
    $added = TRUE;
  }
  drupal_add_js( $settings, 'setting' );
}

/*
* In options array maybe - div, ajaxPath(ajaxid), parents, hide position, trigger, width, fill
*/
